name: Corelibrary Build & Publish 

on:
  push:
    branches: 
      - 'v[0-9]+.[0-9]+'
  pull_request:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Version
      run: |
        echo ${{ github.head_ref }}
        BRANCH=${BRANCH##*/}
        if [[ $BRANCH =~ ^v[0-9]+.[0-9]+$ ]]
        then
          VERSION="${BRANCH#v}.$GITHUB_RUN_NUMBER"
          IS_MASTER_BUILD=1
        else
          VERSION="0.0.0"
          IS_MASTER_BUILD=0
        fi
        echo $BRANCH
        echo $VERSION
        
        echo "::set-env name=VERSION::$(echo $VERSION)"
        echo "::set-env name=IS_MASTER_BUILD::$(echo $IS_MASTER_BUILD)"
      env:
        BRANCH: ${{ github.head_ref }}

    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
      env:
        GIT_COMMIT: ${{ github.sha }}
    - name: Test
      run: dotnet msbuild /t:RunTests /p:Configuration=Release /p:LogFileName=$PWD/test-results/tests.trx
      working-directory: test
